version: '3.8'
networks:
  kscheduler:
    name: kscheduler
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks: 
      - kscheduler
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: 
      - zookeeper
    networks: 
      - kscheduler
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://kafka.local.rhysmccaig.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "kscheduler.input6:1,kscheduler.scheduled:6:1,kscheduler.outgoing:6:1,test.topic.a:6:1,test.topic.b:6:1,test.topic.c:6:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kscheduler:
    build: 
      context: .
    depends_on: 
      - kafka
    networks: 
      - kscheduler
    ports:
      - "8080:80"
    environment:
      KSCHEDULER_KAFKA_STREAMS_APPLICATION_ID: KScheduler
      KSCHEDULER_KAFKA_STREAMS_BOOTSTRAP_SERVERS: "kafka:19092"
      KSCHEDULER_KAFKA_STREAMS_RETRIES: 10
      KSCHEDULER_TOPICS_INPUT: kscheduler.input
      KSCHEDULER_TOPICS_SCHEDULED: kscheduler.scheduled
      KSCHEDULER_TOPICS_OUTPUT: kscheduler.output
      KSCHEDULER_SCHEDULER_MAXIMUM_DELAY: 7d
      KSCHEDULER_SCHEDULER_PUNCTUATE_INTERVAL: 1s
      LOG4J_ROOTLOGGER: DEBUG

      


  